---

- block:
  - name: Create systemd gunicorn service
    template: 
      src: 'gunicorn_daemon.j2'
      dest: '/etc/systemd/system/gunicorn.service'
      mode: '0644'

  - name: Run gunicorn service
    service:
      name: gunicorn
      state: started
      enabled: yes
  become: yes
